export const testPopulator = [
	{ id: '1', name: 'Eddie Alvarez', nationality: 'Transylvanian', house: 'Ravenclaw', gender: "Male", species: "Vampire", image: "https://a.espncdn.com/i/headshots/mma/players/full/2431333.png", blood_status: "Half-blood" },
	{ id: '2', name: 'Rose Namajunas', nationality: 'Moroccan', house: 'Gryffindor', gender: "Female", species: "Veela", blood_status: "Muggle-born" },
	{ id: '3', name: 'Jessica Andrade', nationality: 'Bulgarian', house: 'Slytherin', gender: "Female", species: "Half-giant", blood_status: "Pure-blood" },
	{ id: '4', name: 'Rafael Fiziev', nationality: 'Scottish', house: 'Hufflepuff', gender: "Male", species: "Human", image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4339488.png&w=350&h=254", blood_status: "Unknown" },
	{ id: '5', name: 'Dustin Poirier', nationality: 'Welsh', house: 'Slytherin', gender: "", species: "Werewolf", blood_status: "Half-blood" },
	{ id: '6', name: 'Charles Oliveira', nationality: 'Greek', house: 'Gryffindor', gender: "Male", species: "Goblin", image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2504169.png&w=350&h=254", blood_status: "Pure-blood" },
	{ id: '7', name: 'Islam Makhachev', nationality: 'Romanian', house: 'Ravenclaw', gender: "", species: "Squib", blood_status: "Squib" },
	{ id: '8', name: 'Justin Gaethje', nationality: 'Irish', house: 'Gryffindor', gender: "Male", species: "Centaur", blood_status: "Unknown" },
	{ id: '9', name: 'Mickey Gall', nationality: 'Austrian', house: 'Hufflepuff', gender: "Male", species: "Human", blood_status: "Muggle-born" },
	{ id: '10', name: 'Brandon Moreno', nationality: 'Norwegian', house: 'Ravenclaw', gender: "", species: "Veela", blood_status: "Half-blood" },
	{ id: '11', name: 'Gregor Gillespie', nationality: 'Hungarian', house: 'Gryffindor', gender: "Male", species: "Werewolf", blood_status: "Pure-blood" },
	{ id: '12', name: 'Jose Aldo', nationality: 'Slovenian', house: 'Slytherin', gender: "Male", species: "Goblin", image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2447641.png&w=350&h=254", blood_status: "Half-blood" },
	{ id: '13', name: 'Alexander Gustafsson', nationality: 'Danish', house: 'Ravenclaw', gender: "", species: "Half-giant", image: "https://a.espncdn.com/i/headshots/mma/players/full/2500771.png", blood_status: "Unknown" },
	{ id: '14', name: 'Valentina Shevchenko', nationality: 'Estonian', house: 'Slytherin', gender: "Female", species: "Veela", blood_status: "Pure-blood" },
	{ id: '15', name: 'Michael Chandler', nationality: 'Moldovan', house: 'Hufflepuff', gender: "Male", species: "Human", blood_status: "Muggle-born" },
	{ id: '16', name: 'Carlos Condit', nationality: 'Latvian', house: 'Gryffindor', gender: "", species: "Squib", blood_status: "Squib" },
	{ id: '17', name: 'Michael Bisping', nationality: 'Croatian', house: 'Ravenclaw', gender: "Male", species: "Ghost", blood_status: "Unknown" },
	{ id: '18', name: 'Marvin Vettori', nationality: 'Slovakian', house: 'Hufflepuff', gender: "Male", species: "Centaur", image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4001851.png&w=350&h=254", blood_status: "Half-blood" },
	{ id: '19', name: 'Zhang Weili', nationality: 'Czech', house: 'Gryffindor', gender: "Female", species: "Veela", blood_status: "Muggle-born" },
	{ id: '20', name: 'Bobby Green', nationality: 'Ukrainian', house: 'Slytherin', gender: "", species: "House-elf", blood_status: "Unknown" },
];